CREATE TABLE admin(
aid VARCHAR(8) PRIMARY KEY,
aname VARCHAR(20) NOT NULL,
aphone VARCHAR(11) UNIQUE,
apassword VARCHAR(20) NOT NULL DEFAULT(123456),
remark VARCHAR(255)
)

CREATE TABLE student
(sid VARCHAR(6) PRIMARY KEY,
aid VARCHAR(8) NOT NULL REFERENCES admin(aid),
name VARCHAR(20) NOT NULL,
scollege VARCHAR(100) NOT NULL,
smajor VARCHAR(100) NOT NULL,
semail VARCHAR(100) UNIQUE,
sphone VARCHAR(11) UNIQUE, 
spassword VARCHAR(20) NOT NULL DEFAULT(123456),
syear VARCHAR(10) NOT NULL, 
remark VARCHAR(255)
)

CREATE TABLE teacher(
tid VARCHAR(8) PRIMARY KEY,
aid VARCHAR(8) NOT NULL REFERENCES admin(aid),
tname VARCHAR(20) NOT NULL,
temail VARCHAR(20) NOT NULL,
tphone VARCHAR(11) NOT NULL,
tpassword VARCHAR(20) NOT NULL DEFAULT(123456),
tcollege VARCHAR(100) NOT NULL,
remark VARCHAR(255)
)

CREATE TABLE course(
cid VARCHAR(10) PRIMARY KEY,
sid VARCHAR(6) REFERENCES student(sid),
tid VARCHAR(8) REFERENCES teacher(tid),
aid VARCHAR(8) NOT NULL REFERENCES admin(aid),
cname VARCHAR(20) NOT NULL,
ccollege VARCHAR(100) NOT NULL,
cyear VARCHAR(20) NOT NULL,
cmajor VARCHAR(100) NOT NULL,
remark VARCHAR(255)
)

CREATE TABLE score(
cid VARCHAR(10) REFERENCES course(cid),
sid VARCHAR(6) REFERENCES student(sid),
aid VARCHAR(8) REFERENCES admin(aid),
tid VARCHAR(8) REFERENCES teacher(tid),
susually SMALLINT NOT NULL,
sfinally SMALLINT NOT NULL,
spercent SMALLINT NOT NULL,
srank VARCHAR(5) NOT NULL,
remark VARCHAR(255),
PRIMARY KEY (cid,sid),
UNIQUE (cid,tid)
)
